### ISSUE TITLE
{"error":"invalid_grant"

### ISSUE THREAD

**Issue by aircode10** [CFenner/MMM-Netatmo#100]
Hello,

when I try to get this token with

```
curl --data "grant_type=password&client_id=xxxxx&client_secret=xxxxx&username=xxxxx&password=xxxxx&scope=read_station" "https://api.netatmo.com/oauth2/token"
```

I get this answer: {"error":"invalid_grant"}

I double checked client_id, client_secret, usename and password!

Do you have any other ideas?

Thanks for help...

**Comment by ViggoFrish** [comment]
Use single brackets instedof dobble brackets, worked for me when i did this;

'grant_type=password&client_id=xxxxx&client_secret=xxxxx&username=xxxxx&password=xxxxx&scope=read_station' 'https://api.netatmo.com/oauth2/token')

**Comment by aircode10** [comment]
Thanks for that idea... unfortunatly, it did not help :-(

**Comment by lpmdesign** [comment]
I have the same issue. Maybe something changed with the app creation process at dev.netatmo.com? They ask me for a redirect URI and a webhook URI

**Comment by CFenner** [comment]
With #107 the authentication will be done using username/password, so you no longer need to fetch the token yourself.

**Comment by CFenner** [comment]
Please use the lates module version to simply use username & password for authentication in the mirror config.
