### ISSUE TITLE
Wrong install information

### ISSUE THREAD

**Issue by cyber152** [CFenner/MMM-Netatmo#143]
hi @CFenner 

In the installation insctruction this  : 
cd ~/MagicMirror/modules && git clone git clone https://github.com/CFenner/MMM-Netatmo.git netatmo 

this is wrong a "git clone" is in double

I think that ,it must be  : 
cd ~/MagicMirror/modules && git clone https://github.com/CFenner/MMM-Netatmo.git netatmo 

have a nice day

**Comment by CFenner** [comment]
@all-contributors please add @cyber152 for doc.

**Comment by CFenner** [comment]
Thanks for the hint.
