### ISSUE TITLE
Change Pressure Unit

### ISSUE THREAD

**Issue by Laz2516** [CFenner/MMM-Netatmo#148]
Good afternoon.
I have a RU zone. All data values correspond.
But the pressure is shown in mbar. I need in mmHg. I did not find how to change the settings..... (

**Comment by CFenner** [comment]
This is not implemented. One would need to calculate that, sorry.

**Comment by Laz2516** [comment]
Good afternoon.
Thank you for responding in person...))
It would be very convenient for you to add output to mmHg. Many countries use this pressure format. I am new to this topic, also to the Raspberry topic, but I was able to find how to translate the readings of the modules into Russian. But with pressure it does not work.
I also tried to install the RaymondMolenaar author module
https://github.com/RaymondMolenaar/MMM-Netatmo
but I could not get a token through the cURL and the module did not start.... ((

**Comment by CFenner** [comment]
> I was able to find how to translate the readings of the modules into Russian.

Would really appreciate if you could feed pack the translation via a pull request. 👏

**Comment by Laz2516** [comment]
Good. I'll try to do it. I will slightly adjust the length of words (it should vary depending on the location of the modules on the screen. Full word or abbreviation.).
I just added the ru.json file with translation to the l10n folder.

**Comment by Laz2516** [comment]
To add the translation of data into Russian, you need to add the text file ru.json to the l10n folder with such text. Text abbreviations depend on the location of the modules on the screen. Perhaps the css file has settings that expand the boundaries of the display of modules on the screen, then you can use text without abbreviation....
I use the arrangement of modules on the left, vertically, type bubbles.


{
  "CO2": "CO<sub>2</sub>",
  "NOISE": "Шум",
  "HUMIDITY": "Влажность",
  "PRESSURE": "Давлен",
  "PRESSURE_TREND": "Давлен (изм)",
  "TEMPERATURE": "Темп-ра",
  "TEMP_TREND": "Темп-ра (изм)",
  "RAIN": "Дождь",
  "SUM_RAIN_1": "Дождь (1ч)",
  "SUM_RAIN_24": "Дождь (24ч)",
  "WINDSTRENGTH": "Ветер",
  "WINDANGLE": "Ветер (направл)",
  "GUSTSTRENGTH": "Порыв",
  "GUSTANGLE": "Порыв (направл)",
  "UP": "рост",
  "STABLE": "стаб",
  "DOWN": "упало",
  "UNDEFINED": "неизвестно",
  "WIFI": "WiFi",
  "RADIO": "Ур. сигнала",
  "BATTERY": "Батарея",
  "LAST_MESSAGE": "Посл соед"
}

**Comment by Laz2516** [comment]
Good afternoon! Please help change the pressure unit...)))

**Comment by CFenner** [comment]
goal would be to respect all user settings as described in #24
