### ISSUE TITLE
Netatmo has changed its data access

### ISSUE THREAD

**Issue by MajorC1983** [CFenner/MMM-Netatmo#153]
Netatmo has changed its data access to OAuth2. I guess also the module and the manual must be adapted?

````
Dear Netatmo developer,

To improve the security of our products, we inform you that the Client Credentials grant type method will be completely removed. It will no longer be possible to authenticate with the username and password of the user.

The effective date of this update is October 2022.

How can you authenticate with Netatmo API ?
From this date, the OAuth2 authorization code flow must be followed for authentication.

You can find details on this method on our website:

Netatmo Connect | Authentication
For tests, you can also get an Access Token from our developper portal.

Netatmo Developer Portal

Log in
Go on your account
Select the application for your test
Click on "Generate a Token"

You can now use this Access Token for 3 hours.
```
`

**Comment by tgullii** [comment]
Was about to install this module before I saw this note, seems like I need to wait. Is this module being maintained?

**Comment by CFenner** [comment]
Sorry, I’m not actively maintaining this anymore as my mirror roasted it’s SD card. However I am willing to merge PRs.

**Comment by tgullii** [comment]
@CFenner Understood, thanks!
The OAuth2 was nicely implemented on the [MMM-GoogleCalendar](https://github.com/randomBrainstormer/MMM-GoogleCalendar), if anyone is interested in giving this a go here.

**Comment by MajorC1983** [comment]
Hello,

I think I have triggered a false alarm. I installed the module on a new Raspberry over the weekend and it works.

Best regards

Christian
