### ISSUE TITLE
If AQI is between 101 and 150 the text which will be displayed enlarge the module

### ISSUE THREAD

**Issue by Sorelie** [CFenner/MMM-Netatmo#154]
If the AQI is between 101 and 150 the text "Unhealthy for sensitive groups (EN)/Ungesund für empfindliche Personengruppen (DE)" enlarge the module size. Could you abbreviate the text or use alternative text? "Maybe unhealthy (EN)/Möglicherweise ungesund (DE)"

**Comment by CFenner** [comment]
This module does not provide AQI.
