### ISSUE TITLE
Pressure settings in mmHg

### ISSUE THREAD

**Issue by Laz2516** [CFenner/MMM-Netatmo#156]
I have pressure settings in mmHg. So I get in the application and in the web interface. But in a smart mirror, I have pressure in other units. How do I get a display in mmHg?
![image](https://user-images.githubusercontent.com/40304797/224991198-34713e87-13c6-436d-a084-361d882c84e3.png)
![image](https://user-images.githubusercontent.com/40304797/224991382-198af54a-d427-498f-ab83-a4b5e8ce1ab5.png)

![image](https://user-images.githubusercontent.com/40304797/224991537-332d4e6e-eccd-4327-adc5-b1d9f3694f5d.png)

**Comment by CFenner** [comment]
duplicates #148
