### ISSUE TITLE
Decimal place for rain-sensor

### ISSUE THREAD

**Issue by Raipel** [CFenner/MMM-Netatmo#26]
Hello,
is it possible, that the module shows the decimal place from the rain-sensor? Now, wehn it rains a little bit (e.g. 0,3mm) the module shows "Niederschlag 0" and not "Niederschlag 0.3". Can anyonw say me, where I can update the code, so that I can see the decimal place? Tahnk you very much!
Sorry for my bad english.

**Comment by CFenner** [comment]
Hey @Raipel,

There is an object called "formatted", where the formatting is done.

If you like to adjust it yourself, feel free to do a pull request. 

Best regards

Christopher

**Comment by CFenner** [comment]
@Raipel can you check the formatting now?
