### ISSUE TITLE
Netatmo > thermostat ?

### ISSUE THREAD

**Issue by fastenspy** [CFenner/MMM-Netatmo#27]
Hello,

Is it possible to have the thermostat information and not the weather station?

**Comment by CFenner** [comment]
currently not, but the [API](https://dev.netatmo.com/resources/technical/reference/thermostat/getthermostatsdata) is avilable. What would you like tho see there?

**Comment by fastenspy** [comment]
Hello, yes as on the thermostat. The state of the thermostat with the target temperature. And also the temperature of the room ...

**Comment by CFenner** [comment]
There is a [Netatmo thermostat module](https://github.com/overfl0w11/MMM-Netatmo-Thermostat) available.
