### ISSUE TITLE
Can't get the refresh_token: [REFRESH_TOKEN]

### ISSUE THREAD

**Issue by ak-media** [CFenner/MMM-Netatmo#29]
Hi Christopher,
I just tried to configure your Netatmo-Module, but I can't get the refresh_token via Hurl.it.

I just get an "400 Bad Request" from POST https://api.netatmo.com/oauth2/token

Where is the trick? ;)

Cheers
KC

**Comment by CFenner** [comment]
Hm.. maybe there was an API change? I should refactor this authentication stuff :(

If my kid is not keeping me running this evening i'll try to have a look at it!

**Comment by ak-media** [comment]
I just generated the API an hour ago… ;)

**Comment by ak-media** [comment]
Maybe it is because I filled in "password" at "gant_type"? What is "gant_type"?

**Comment by ak-media** [comment]
I fpund the it: it'S the missing "r" in "gant_type". ;)
