### ISSUE TITLE
Trying to install, but wont get any data

### ISSUE THREAD

**Issue by cgillinger** [CFenner/MMM-Netatmo#312]
Hi and happy new year to you all!

I've been running this module on a Windows machine for quite some time, but that had to be repurposed. So, now I'm trying to get it running on a Raspberry Pi, but I've struck a wall of sorts.

I've read around here and otherwere, that there has been issues with Netatmo changing their way of accepting credentials and Im hoping my issues are caused by this, but I'm not sure. It can also be that I'm just stupid, Im not that well versed in Linux. 

I've installed the module, the process were pretty much similar as on my old windows install. But when I run it not only is the module stuck on "loading", but all other modules get stuck in "loading" as well.

I've tried to boil it down to basics, using the standard default config.js. With just the out-of-the-box config.js, the modules for news/clock/US holidays load just fine.

When I add the Netatmo module, it, toghether with news and US Holidays get stuck on "loading". 

Could you guys help me out here? Any and all help would be greatly appreciated.

**Comment by CFenner** [comment]
Just did a fresh install with Docker (`karsten13/magicmirror:latest`, v2.26.0) and added the modules without any issues. Are you sure you did alle the required steps? You need to install dependencies as mentioned [here](https://github.com/CFenner/MMM-Netatmo#installation).

**Comment by cgillinger** [comment]
> Just did a fresh install with Docker (`karsten13/magicmirror:latest`, v2.26.0) and added the modules without any issues. Are you sure you did alle the required steps? You need to install dependencies as mentioned [here](https://github.com/CFenner/MMM-Netatmo#installation).

I think I did. I followed the instructions from the Github repository and every other module worked perfectly. I'll try again, this time on a full Ubuntu installation as opposed to the Raspian one (the Pi is horrible to troubleshoot in, since its so slow).

I'll try again, and report back here.

**Comment by cgillinger** [comment]
And very fast: Yes! Got it to work on my Ubuntu setup. However for some reason the module is in what appears to be Hungarian. I have no idea why. And I cant seem to get the "horizontal='false'" to work, eg to get the module to not span horizontally. 

Any ideas (especially when it comes to language, the config.js has "language: "sv",locale: "sv-SE"," set.)

**Comment by CFenner** [comment]
> the Pi is horrible to troubleshoot in, since its so slow

I recommend to run the mirror itself on a NAS or similar in server mode and only use the raspi to display that page.

**Comment by cgillinger** [comment]
And to update: Setting default language to en_us in config.js means the module shows in english. Changing to swedish, gives hungarian instead.

**Comment by CFenner** [comment]
> I cant seem to get the "horizontal='false'" to work

Did you try `horizontal=false` without the quotes? 

This works for me.
```
                {
                  module: 'netatmo',
                  position: 'bottom_left', // the location where the module should be displayed
                  header: 'Netatmo', // a header if you like one
                  config: {
                    horizontal: false,
                    clientId: '', // your app id
                    clientSecret: '', // your app secret
                    access_token: '',
                    refresh_token: '', // your generated refresh token
                  }
                },
```


> For some reason the module is in what appears to be Hungarian.

There is no translation for `sv` though `cs` is probably picked: https://github.com/CFenner/MMM-Netatmo/tree/main/l10n

Translation PRs are very welcome!

**Comment by cgillinger** [comment]
{
  "CO2": "CO²",
  "NOISE": "Ljudnivå",
  "HUMIDITY": "Luftfuktighet",
  "PRESSURE": "Lufttryck",
  "PRESSURE_TREND": "Lufttryck (trend)",
  "TEMPERATURE": "Temperatur",
  "TEMP_TREND": "Temperatur (trend)",
  "RAIN": "Regn",
  "SUM_RAIN_1": "Regn (1h)",
  "SUM_RAIN_24": "Regn (24h)",
  "WINDSTRENGTH": "Vindstyrka",
  "WINDANGLE": "Vind (riktning)",
  "GUSTSTRENGTH": "Byar",
  "GUSTANGLE": "Byar (riktning)",
  "UP": "stigande",
  "STABLE": "stabilt",
  "DOWN": "fallande",
  "UNDEFINED": "inte tillgänglig",
  "WIFI": "WiFi",
  "RADIO": "Radiosignal",
  "BATTERY": "Batteri",
  "LAST_MESSAGE": "senaste meddelande"

**Comment by CFenner** [comment]
Thanks, you need to add the new file, like here: https://github.com/CFenner/MMM-Netatmo/pull/82/files

**Comment by cgillinger** [comment]
I think I just did. This is my first time doing anything other than downloading from GitHub, so I really hope I did it correctly.

**Comment by cgillinger** [comment]
> > I cant seem to get the "horizontal='false'" to work
> 
> Did you try `horizontal=false` without the quotes?
> 
> This works for me.


That did the trick, thnx!
