### ISSUE TITLE
Wind in km/h

### ISSUE THREAD

**Issue by y0m1g** [CFenner/MMM-Netatmo#374]
Hello,

I may be mistaking or have missed a configuration somewhere, but I believe the wind unit is hardcoded to `m/s`: https://github.com/CFenner/MMM-Netatmo/blob/ce90c9503a9c64771f82d5c3c3a9faa6935a5ad1/netatmo.js#L288
(my locale is `fr-CA` and `units` is set to `metric` in MM config)

Could it be possible to add an option to display in `km/h` instead?

Thanks a lot for the great work on this plugin!

**Comment by CFenner** [comment]
See #24

**Comment by y0m1g** [comment]
Even though user preferences units need are still to implement, the current wind unit is wrong:
https://github.com/CFenner/MMM-Netatmo/issues/374

**Comment by CFenner** [comment]
Thanks for the PR, will try to have a look at the user-preferred units.
