### ISSUE TITLE
Possible Issue at Startup

### ISSUE THREAD

**Issue by mumblebaj** [CFenner/MMM-Netatmo#380]
Hi,

I have noticed a few people posting that the module is not working when they startup in the morning. I believe that the below code is where the issue is.

```
    // get a new token at start-up. When receive, GET_CAMERA_EVENTS will be requested
    setTimeout(function () {
      self.sendSocketNotification(self.notifications.DATA, self.config)
    }, this.config.initialDelay * 1000)
```

I believe that you may want to call `self.notifications.AUTH` at startup which would then get a new token using the old token it had. Unless I am mistaken. 

Can you please check this out?

Thanks

**Comment by Gabian34** [comment]
Hi,

Same issue at startup since a few days, no change when replacing DATA by AUTH in the module code. The only way to display informations is to generate a new refresh token but the problem appears again at next MM launch.

**Comment by Empyreum** [comment]
Hi,

I'm experiencing the same issue here.
As @Gabian34 mentioned it can be solved by generating a new refresh token, but will be a problem again on next startup of the module.

**Comment by swopeman** [comment]
Hi,

I also have these errors like @Empyreum @Gabian34

**Comment by Gabian34** [comment]
Hi, @bugsounet fixed it in his MMM-NetatmoThermostat module (same API … so same Issue). Solution consists in stocking a token in token.json local file. I m not a developper , so if someone could apply his solution...

**Comment by haywirecoder** [comment]
Hi, per Netamo documentation the refresh token periodic changes (e.g. expires), the code automatically gets a new one when updating the data. So as long as you don't re-start everything will work as expected. However, once you restart the code no longer knows the valid refresh token and you have to manual create a new one on the Netatmo dev site.  I have a very modified fork of this module for awhile ago, so the base (module)  code is not the same. However, I believe my updated to  helper.js will work for this installation and will correct issue by creating cache of the refresh token. It located here .... https://github.com/haywirecoder/MMM-Netatmo/blob/master/helper.js. Keep in mind the refresh token is only validate for about 3hrs, so if the module is down for an extend time you will have manual generate a token on the web portal

**Comment by bugsounet** [comment]
No... From doc, When authenticate `Netatmo` server will send an access_token (for any query) AND it will send NEXT refresh token to use when access_token expire (10800 sec)

So... just save token result on authenticate and use saved refresh_token 

Let's Restart MM² with this rule:
```js
[2024-06-14 12:10:31.030] [LOG]   [NETATMO] Starting MMM-NetatmoThermostat module... 
[2024-06-14 12:10:31.031] [LOG]   [NETATMO] Use token.json for Authenticate 
[2024-06-14 12:10:32.135] [LOG]   [NETATMO] token.json was written successfully 
[2024-06-14 12:10:32.136] [LOG]   [NETATMO] Authenticated! 
[2024-06-14 12:10:32.138] [LOG]   [NETATMO] Token Expire Friday, June 14, 2024 3:09 PM 
```

access_token on config file is used ONLY on the first authenticate (first use of the module) and is no longer used after On restart of MM² must use saved token file (check presence of the file)

For helping from my module `MMM-NetatmoThermostat`:
 * It's not the same module but API is the same (only used for `read_thermostat` scope) 
 * this is [my change](https://github.com/bugsounet/MMM-NetatmoThermostat/pull/21/files)
 
It's up to you to adapt it to this module
I have no weather station for make a PR and test it

@bugsounet

**Comment by CFenner** [comment]
Thanks! I'll try to reserve some time on the weekend to look at this.

**Comment by bugsounet** [comment]
No problem, Thanks for them ;)

**Comment by mumblebaj** [comment]
Thanks @CFenner  and @bugsounet

**Comment by swopeman** [comment]
Is there anything new?

**Comment by bugsounet** [comment]
need help @CFenner ?

**Comment by bugsounet** [comment]
(because i'm kind, i will code it)

**Comment by bugsounet** [comment]
Good news:

 * I finish to recode it ;))
 * Tested successfully by @Lusbueb69

**Comment by Lusbueb69** [comment]
> Good news:
> 
> * I finish to recode it ;))
> * Tested successfully by @Lusbueb69

i have choose an this way to test:

- `pm2 stop mm`
- rename the existing folder `netatmo` to `netatmo.240622`
- `cd ~/MagicMirror/modules && git clone https://github.com/bugsounet/MMM-Netatmo netatmo`
- `cd netatmo && npm ci --production --ignore-scripts`
- generate a new [refresh-token](https://dev.netatmo.com/apps/) an insert the new token in `config.js`
- `pm2 start mm`

i'm so happy, everything works fine, still after a RPI reboot or a `pm2 restart mm`.

**Comment by bugsounet** [comment]
I 'm not completely agree with this method because I will destroy my fork once the modifications are made on the @CFenner repo

So... it's only for testing :)
In All case, Happy use!

**Comment by Gabian34** [comment]
@bugsounet Good job, it works perfectly ! Many thanks for your help ...

**Comment by bugsounet** [comment]
Right !

@CFenner have merge my [Pull Request](https://github.com/CFenner/MMM-Netatmo/pull/382)

Thanks for this testing but you have to return to @CFenner repository and make a `git pull`
I will delete my fork, so that @CFRunner have the exclusivity of this module

Happy use,
@bugsounet

**Comment by mumblebaj** [comment]
Fix merged from @bugsounet
