### ISSUE TITLE
Wind is always displayed in km/h

### ISSUE THREAD

**Issue by Duhlin12** [CFenner/MMM-Netatmo#384]
I am having trouble getting the wind module to display in m/s. The unit displayed is m/s, but the value is in km/h. I have a config parameter that is "windUnit: "MS", // Possible "KMH", "MPH", "MS", "BFT", "KT". What am I missing?

regards 
Daniel

**Comment by CFenner** [comment]
I think the module needs to translate the values itself. The api gives a users preference but the value will always be kph.

**Comment by CFenner** [comment]
duplicates #24
