### ISSUE TITLE
How to Update Netatmo Module?

### ISSUE THREAD

**Issue by Denn2705** [CFenner/MMM-Netatmo#393]
Hello, 

i got the Message on my MM that there is an update available for "netatmo" module.

Is there any way to easily update the module without need to delete and reinstall/reconfigure it?

If i try the initial installation command, i get the response 
"fatal: destination path 'netatmo' already exists and is not an empty directory."

Thanks for the support!
Br
Dennis

**Comment by CFenner** [comment]
Yes, you just need to update the git branch. Change to the netatmo folder and type 'git pull'.

**Comment by Denn2705** [comment]
Thanks for the explanation! Im not so familiar with git yet :-)

Br
Dennis
