### ISSUE TITLE
Uncaught TypeError: Cannot read property of 'body' of undefined

### ISSUE THREAD

**Issue by adriancoleman** [CFenner/MMM-Netatmo#49]
MagicMirror v2.1.2
RPi 3  Linux 4.9.41-v7+ #1023 armv71 GNU/Linux

I confess to being a newbie but having spent a week or so attempting to investigate, trawling the web and following the code, I have been unable to make the Netatmo module of MagicMirror work.  Thus I am seeking guidance...

So far I have;

- created an app at dev.netatmo.com
- verified that my access token is valid
- successfully pulled raw data from the Netatmo API for my Weather Station (using Postman)
- stripped out all other modules in my config,js
- re-installed the Netamo module from the git

Upon running MagicMirror (pm2 start mm.sh) I see only a spinning circle where I expect to see the Netatmo data.

Running via "npm start dev" the console reports;

```
  _netatmo.js:114 error [object Object]
  q.min.js:1 Uncaught TypeError: Cannot read property 'body' of undefined
      at Class.renderAll (netatmo.js:105)
      at e (q.min.js:1)
      at h.promiseDispatch.j (q.min.js:1)
      at o.d.promiseDispatch (q.min.js:1)
      at q.min.js:1
      at b (q.min.js:1)
      at MessagePort.a (q.min.js:1)
renderAll @ netatmo.js:105
e @ q.min.js:1
h.promiseDispatch.j @ q.min.js:1
d.promiseDispatch @ q.min.js:1
(anonymous) @ q.min.js:1
b @ q.min.js:1
a @ q.min.js:1_
```

I have very little experience and am continuing to research and follow all of the components.  In the meantime I would very much appreciate assistance in investigating.

Please advise if additional information is required or, indeed, if I am doing something stupid!

Many thanks,
Adrian Coleman

**Comment by CFenner** [comment]
Please reopen if error still exists with the current code.
