### ISSUE TITLE
Select moduls and messuring sensor, How??

### ISSUE THREAD

**Issue by jegerikke** [CFenner/MMM-Netatmo#51]
Can someone please make a example of where to put the moduleOrder and  dataOrder code.

i have tried to do some in config.js but the MM wont approve the file.

	                module: "netatmo",
	                position: 'bottom_right', // the location where the module should be displayed
	                config: {
		                clientId: 'xxxxxx', // your app id
		                clientSecret: 'xxxxx', // your app secret
		                refreshToken: 'xxxx' // your generated refresh token
                        moduleOrder: "Verksted"

**Comment by CFenner** [comment]
Hi @jegerikke, configure it like this:

```
module: 'netatmo',
...
config: {
  ...
  moduleOrder: ['Garage','Garden'],
  dataOrder: ['Noise','Pressure','CO2']
},
```

**Comment by jegerikke** [comment]
Hi

still cant figure this out. shall i put the code in the config.js or in the netatmo.js file?
can the problem be that i have netatmo in norwegian?
is is possible to change the text on det bubbles to norwegian?

**Comment by CFenner** [comment]
You need to configure the module in the `config.js` as for other modules as well. (https://github.com/CFenner/MMM-Netatmo#configuration)

Norwegian language would be possible in general, but someone needs to do the translation work.

**Comment by jegerikke** [comment]
if you send a word list i can try to translate.

**Comment by CFenner** [comment]
please see #52 for the translation

how about the module, did you manage to configure it?

**Comment by jegerikke** [comment]
Her is the translation:


"CO2": "CO<sub>2</sub>",
 +  "NOISE": "Støy",
 +  "HUMIDITY": "Luftfuktighet",
 +  "PRESSURE": "Lufttrykk",
 +  "PRESSURE_TREND": "Lufttrykk (trend)",
 +  "TEMPERATURE": "Temperatur",
 +  "TEMP_TREND": "Temperatur (trend)",
 +  "RAIN": "Regn",
 +  "SUM_RAIN_1": "Regn (1t)",
 +  "SUM_RAIN_24": "Regn (24t)",
 +  "WINDSTRENGTH": "Vind",
 +  "WINDANGLE": "Vind (retning)",
 +  "GUSTSTRENGTH": "Vindkast",
 +  "GUSTANGLE": "Vindkast (retning)",
 +
 +  "UP": "Økende",
 +  "STABLE": "Stabilt",
 +  "DOWN": "Fallende",
 +  "UNDEFINED": "Ikke tilgjengelig",
 +
 +  "WIFI": "WiFi",
 +  "RADIO": "Radio signal",
 +  "BATTERY": "Batteri",
 +  "LAST_MESSAGE": "Sist kontakt"

**Comment by jegerikke** [comment]
Yes i figured i out. i forgot to set a comma on the last required line.

i have set the showbattery to false but i still show bat% any idea?

is it a way to make the bubble layout smaller? and only have the "main" readings showing.(removing temp. trend small text and the co2 reading?

**Comment by jegerikke** [comment]
Hii

i cant find any place to change for english to norwegian.

where do i change it?

**Comment by CFenner** [comment]
In the magicmirror config, the Module inherits from there.

**Comment by jegerikke** [comment]
Ok. then i think the naming i wrong. we have two writing language in Norway.  i see in the MM config that they support both. its nb and nn ,the translation i gave you is for nb. so can it be that you named it no taht is the problem?

**Comment by CFenner** [comment]
@jegerikke please verify the translation, thanks!

**Comment by jeremyfritzen** [comment]
Hi guys, can we close this issue as @jegerikke finally managed to solve his original problem (selecting moduls and messuring sensor). Thank you!

**Comment by CFenner** [comment]
@all-contributors please add @jegerikke for translation
