### ISSUE TITLE
design: 'bubbles' not showing + hideLoadTimer not working

### ISSUE THREAD

**Issue by Galmior** [CFenner/MMM-Netatmo#79]
Hello,

I am trying to use your module. I was configuring it and found this 2 parameters design and hideLoadTimer
I added in my config.js but nothing changes on ma MM screen.
here the config of my module 
```
		{
			disabled: false,
			module: "netatmo",
			position: "top_right", // the location where the module should be displayed
			design: 'bubbles',
			header: "Température by Netatmo",
			hideLoadTimer: true,
			// classes: 'default everyone', 
			config: {
				clientId: "", // your app id
				clientSecret: "", // your app secret
				refreshToken: "", // your generated refresh token
				refreshInterval: "10",
				moduleOrder: ["Salon","Chambre"],
				dataOrder: ["Temperature","Noise","CO2","Humidity","Rain"]
			}
```
Data are showing properly
Could you help on it?

Thanks a lot

Galm

**Comment by Zwirbel1** [comment]
If you are still interested in the solution:

You will have to put the part design: 'bubbles' inside the config part, then it works.
