### ISSUE TITLE
Only rotating circle, no data show

### ISSUE THREAD

**Issue by 1975felix** [CFenner/MMM-Netatmo#80]
The module start in the right position but only a rotating circle displayed on screen.
What's happen?
maybe possible italian translation?

thank you

**Comment by tomlarse** [comment]
I had this as well, and this was a real headscratcher. The config is case sensitive, and it turned out that I had typed `clientID:` when it is supposed to be `clientId:`

I would suggest taking a look at the cases, per the readme they are supposed to be `clientId, clientSecret, refreshToken, refreshInterval, moduleOrder, dataOrder`

**Comment by 1975felix** [comment]
Thank you for answer i check this but is write correct… Is possible yhat the problem was the Language, i'm italian and dataOrder is in english

**Comment by 1975felix** [comment]
How can i check if i have error in config? log file?

**Comment by tomlarse** [comment]
I have no idea really :/ I was looking around for logs as well, but there doesn't seem to be any. 

I don't think it is the language. I changed my config to `language: "it"` and the module still worked.

**Comment by 1975felix** [comment]
I had check everything, in config parameter of the module but no data receve… is a headscratcher real

**Comment by 1975felix** [comment]
tomlarse could you paste your module config stored in config.js. obviously with sensible parameter hide. i try to check the difference

**Comment by tomlarse** [comment]
I can, here it is:

```
{
         module: "netatmo",
         position: "top_right",
         config: {
               clientId: "",
               clientSecret: "",
               refreshToken: "",
               moduleOrder: ["Kjøkken","Verandaen"],
               dataOrder: ["Temperature","Humidity","Noise","CO2","Pressure"
         }
 }
```

**Comment by 1975felix** [comment]
Thank you, unfortunatly is the same as mine… now i have finished ideas

**Comment by 1975felix** [comment]
finally have win…. i find an error in refresh token, for no reson some number been lost ):

**Comment by gitacaza** [comment]
I'm making progress (I had a missing coma in the config file). Now I can see "updated xx min ago" message and still the rotating circle next to it...

**Comment by gitacaza** [comment]
and finally for me the moduleOrder and dataOrder parameters were mandatory... Now everything in order. Thanks :)

**Comment by jeremyfritzen** [comment]
Great !
I think we can close the issue :)
