### ISSUE TITLE
Support for multiple Netatmo weather stations

### ISSUE THREAD

**Issue by thomasberglund** [CFenner/MMM-Netatmo#81]
Hi,

I have tried adding an additional variable for "device_id", to make it possible to add multiple Netatmo weather stations by adding multiple instances of the module in **~/MagicMirror/config/config.js**

https://dev.netatmo.com/resources/technical/reference/weather/getstationsdata

I can see the **device_id** when accessing the Netatmo API (see link above) but I'm struggling a bit getting it to work in this module.

 **~/MagicMirror/config/config.js**
```javascript
{
        module: 'netatmo',
        position: 'bottom_left', // the location where the module should be displayed
        config: {
                clientId: '', // your app id
                clientSecret: '', // your app secret
                refreshToken: '', // your generated refresh token
                deviceId: '' // MAC-address of your device (weather station)
        }
},
```

I added **device_id** to the **dataPayload** variable and added **deviceId** as a new variable to the config part of the **netatmo.js** – but I'm stuck at how to make the call for station data ask for the **device_id**. What am I doing wrong? :)

 **~/MagicMirror/modules/netatmo/netatmo.js**
```javascript
dataPayload: 'access_token={0}&device_id={1}' // added device_id
```

```javascript
 load: {
    token: function() {
      return Q($.ajax({
        type: 'POST',
        url: this.config.api.base + this.config.api.authEndpoint,
        data: this.config.api.authPayload.format(
            this.config.refreshToken,
            this.config.clientId,
            this.config.clientSecret,
            this.config.deviceId) // added deviceId
      }));
    },
    data: function(data) {
      // Log.info(this.name + " token loaded "+data.access_token);
      this.config.refreshToken = data.refresh_token;
      // call for station data
      return Q($.ajax({
        url: this.config.api.base + this.config.api.dataEndpoint,
        data: this.config.api.dataPayload.format(data.access_token) // how do I add deviceId here?
      }));
    }
  },
```

Thomas

**Comment by aop-ch** [comment]
Hi Thomas
I have also multiple Netatmo stations in one account. Did you find a way to select one with device_id?
Kind regards,
Stefan

**Comment by Okiev** [comment]
Hi, I have the same problem. Does anyone already solved the issue?
Best, Okiev

**Comment by aop-ch** [comment]
I used a workaround:

1.copy the module to different folders:
> git clone https://github.com/CFenner/MagicMirror-Netatmo-Module.git netatmo0
> git clone https://github.com/CFenner/MagicMirror-Netatmo-Module.git netatmo1
> git clone https://github.com/CFenner/MagicMirror-Netatmo-Module.git netatmo2

2. rename the netatmo.js to match the name with the directory name
> mv netatmo.js netatmo0.js
> mv netatmo.js netatmo1.js
> mv netatmo.js netatmo2.js

3. Rename the module name in each netatmo0.js file
> Row 8: Module.register('netatmo0', {
and change the device number to 1 to use the second Netatmo Station and 2 for the third.
> Row 105: var device = data.body.devices[0];

4. Register the modules three times with the names "netatmo0","netatmo1","netatmo2" in the config.js file

done

**Comment by Okiev** [comment]
Great, Thanks a lot! Will try.

**Comment by kupraez** [comment]
I tried it but it did't work as mentioned. I can figure it out to get the data from every station individually but not together. Either one or the other is displayed but if i use both modules (netatmo0 and netatmo1) i can't get it working?

**Comment by aop-ch** [comment]
Multiple instances for each station would allow individual placement on the screen.

**Comment by kupraez** [comment]
Hello Christopher, I have a second station in my front-yard (second outdoor module) but the mirror only shows one module. I would prefer multiple stations rendered in one module. That would be great if it works, thank you for your support!

Greetings
Kai-Uwe
