### ISSUE TITLE
disable battery status

### ISSUE THREAD

**Issue by nco1512** [CFenner/MMM-Netatmo#83]
hi,
is there a way to disable the battery status from the outdoor-module in the classic desgin? I've already changend "showBattery" to false in the netatmo.js file but its still there.

**Comment by CFenner** [comment]
hm.. `showBattery` is correct, it should get disable: https://github.com/CFenner/MMM-Netatmo/blob/master/netatmo.js#L470

Is the code uptodate (not cached)?

**Comment by nco1512** [comment]
` addBattery: function(parent, module){
            if(that.config.showBattery)
              this.addData(parent, 'Battery', module.battery_percent);
          },`
it looks just like this.

I got the same issue with `hideLoadTimer: true,`. the LoadTimer is still there.

**Comment by ax42** [comment]
I have a similar issue: Battery is showing on all modules even though I have
`dataOrder: ["Temperature","CO2"]`

**Comment by CFenner** [comment]
Should work as expected in both designs now.
