### ISSUE TITLE
mmm-netatmo shows 'waiting circle' when one netatmo module is not reporting back

### ISSUE THREAD

**Issue by jinjirosan** [CFenner/MMM-Netatmo#85]
Hi Christopher,
I have the main Netatmo module, two indoor modules and one outdoor module. MMM-Netatmo works perfectly when all the netatmo's are reporting in. 

If one or more modules are 'not connected' or 'out of range' (main module and indoor module or on the far edges of the house so sometmes they loose connection), mmm-Netatmo shows only the 'waiting circle' (doesn't display any of the working modules).

I don't mind a warning message for the out-of-range module and have the remaining modules display their stats.

Any suggestions on how to resolve?

**Comment by esjani** [comment]
Great that I found this comment, same issue for me

**Comment by CFenner** [comment]
With #114 the module is simply not showing up. A notification about the disconnect would be good though.

**Comment by CFenner** [comment]
With #135 the broken connection is visualized.
