### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by Raven4150** [CFenner/MMM-Netatmo#93]
Hi, I am new to the whole Raspberry Pi thing and the MagicMirror is one of my first projects. I have managed to get local and global time local news and weather into the magic mirror but implementing Netatmo I am not able to. I have installed the Netatmo Module, updated the Magic Mirror config file, but still t doesn't show. What do I miss? Thanks for your help.

**Comment by CFenner** [comment]
Did you acquire an app token?

see https://github.com/CFenner/MMM-Netatmo#register-an-app

**Comment by Raven4150** [comment]
Hi thanks for your reply. I have really no clue where to get an refresh token. Is there a chance to guide me through that?

**Comment by CFenner** [comment]
That should be described behind that link, but seems to have moved. 

Von meinem iPhone gesendet

**Comment by Raven4150** [comment]
Ok. Is there any chance you could help me with that.

**Comment by Raven4150** [comment]
Can someone help me where I could get the refresh token. I have everything else from the Netatmo API site but I really can't find where II can find the token part. Thanks for your help.

**Comment by Raven4150** [comment]
Done.  Resolved
