### ISSUE TITLE
second netatmo?

### ISSUE THREAD

**Issue by kupraez** [CFenner/MMM-Netatmo#98]
I've two netatmo-station installed in my garden (front- und backyard). The module don't show the datas from the second station? is there anybody who can give me a hand or is the Netatmo api the limiting factor?

**Comment by CFenner** [comment]
Is this still an issue?

do you have two locations (stations/homes) or just another outdoor module?

**Comment by kupraez** [comment]
Hello, yes it is. I Have a second station in my front-yard (second outdoor module) but the mirror only shows one module. I would prefer multiple stations rendered in one module.

**Comment by CFenner** [comment]
Do you use the `classic` or `bubbles` design (default is `classic`)?

**Comment by kupraez** [comment]
In my office I’m using the classic design, but I prefer, I’m honest, the raymondmolennar fork I’m using in my bathroom! I like the icons/view very much.

greetings
Kai-Uwe
